# Generated by Django 3.1.2 on 2024-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=150)),
                ('lieu', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='uploads/images')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('categorie', models.CharField(max_length=150)),
                ('proprietaire', models.CharField(max_length=150)),
            ],
        ),
    ]
